// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjX22xrRaG_CwHVHxRCMpOJlxTfcxECzY',
    appId: '1:835300494968:web:ae9eddad53df018d03278d',
    messagingSenderId: '835300494968',
    projectId: 'notify-63a4a',
    authDomain: 'notify-63a4a.firebaseapp.com',
    storageBucket: 'notify-63a4a.appspot.com',
    measurementId: 'G-M78EWX8BY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFjkjohG-Yg4LX8CpWrLPEC_oP3-1J9A',
    appId: '1:835300494968:android:582b0fb7d3369ebc03278d',
    messagingSenderId: '835300494968',
    projectId: 'notify-63a4a',
    storageBucket: 'notify-63a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuRIHSE6ezAbdqTq3489yKXJ31fsy_xG0',
    appId: '1:835300494968:ios:4605cd336cb3628503278d',
    messagingSenderId: '835300494968',
    projectId: 'notify-63a4a',
    storageBucket: 'notify-63a4a.appspot.com',
    iosClientId: '835300494968-gjasik1ianlb4h2kbavt8dh4m0n5ise9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuRIHSE6ezAbdqTq3489yKXJ31fsy_xG0',
    appId: '1:835300494968:ios:4605cd336cb3628503278d',
    messagingSenderId: '835300494968',
    projectId: 'notify-63a4a',
    storageBucket: 'notify-63a4a.appspot.com',
    iosClientId: '835300494968-gjasik1ianlb4h2kbavt8dh4m0n5ise9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify',
  );
}
